on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.9"
          cache: "poetry"
      - name: Install dependencies
        run: |
          poetry install --with dev
      - name: Run tests
        run: |
          poetry run pytest -vvv
